## Sorting

In [1]:
versioninfo()

Julia Version 1.0.5
Commit 3af96bcefc (2019-09-09 19:06 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)


In [2]:
# Loading the required libraries
using DataFrames

In [3]:
# Load some data
x = [1,3,5,2,1,4]

6-element Array{Int64,1}:
 1
 3
 5
 2
 1
 4

In [5]:
?sortperm

search: sortperm sortperm! partialsortperm partialsortperm! isconcretetype



```
sortperm(v; alg::Algorithm=DEFAULT_UNSTABLE, lt=isless, by=identity, rev::Bool=false, order::Ordering=Forward)
```

Return a permutation vector `I` that puts `v[I]` in sorted order. The order is specified using the same keywords as `sort!`. The permutation is guaranteed to be stable even if the sorting algorithm is unstable, meaning that indices of equal elements appear in ascending order.

See also [`sortperm!`](@ref).

# Examples

```jldoctest
julia> v = [3, 1, 2];

julia> p = sortperm(v)
3-element Array{Int64,1}:
 2
 3
 1

julia> v[p]
3-element Array{Int64,1}:
 1
 2
 3
```

---

```
sortperm(df::AbstractDataFrame, cols;
         alg::Union{Algorithm, Nothing}=nothing, lt=isless, by=identity,
         rev::Bool=false, order::Ordering=Forward)
```

Return a permutation vector of row indices of data frame `df` that puts them in sorted order according to column(s) `cols`.

`cols` can be any column selector (`Symbol`, string or integer; `:`, `All`, `Between`, `Not`, a regular expression, or a vector of `Symbol`s, strings or integers).

If `alg` is `nothing` (the default), the most appropriate algorithm is chosen automatically among `TimSort`, `MergeSort` and `RadixSort` depending on the type of the sorting columns and on the number of rows in `df`. If `rev` is `true`, reverse sorting is performed. To enable reverse sorting only for some columns, pass `order(c, rev=true)` in `cols`, with `c` the corresponding column index (see example below). See other methods for a description of other keyword arguments.

# Examples

```jldoctest
julia> df = DataFrame(x = [3, 1, 2, 1], y = ["b", "c", "a", "b"])
4×2 DataFrame
│ Row │ x     │ y      │
│     │ Int64 │ String │
├─────┼───────┼────────┤
│ 1   │ 3     │ b      │
│ 2   │ 1     │ c      │
│ 3   │ 2     │ a      │
│ 4   │ 1     │ b      │

julia> sortperm(df, :x)
4-element Array{Int64,1}:
 2
 4
 3
 1

julia> sortperm(df, (:x, :y))
4-element Array{Int64,1}:
 4
 2
 3
 1

julia> sortperm(df, (:x, :y), rev=true)
4-element Array{Int64,1}:
 1
 3
 2
 4

 julia> sortperm(df, (:x, order(:y, rev=true)))
 4-element Array{Int64,1}:
  2
  4
  3
  1
```


In [9]:
# sortperm returns the permutation vector of rows
idx = sortperm(x)
# You can sort them using the permutation vector as follows:
sorted_x = x[idx]
@show sorted_x;

sorted_x = [1, 1, 2, 3, 4, 5]


In [10]:
# You can also sort in descending order with the rev argument
idxD = sortperm(x, rev=true)
decreasing_x = x[idxD]
@show decreasing_x;

decreasing_x = [5, 4, 3, 2, 1, 1]


In [19]:
# Sorting a DataFrame
@show dat = DataFrame(X = [1,2,3,1], Y = [7,19,2,2])
# Sort on X
idxX = sortperm(dat[!,:X])
@show dat = dat[idxX, :]
# Alternatively, 
@show dat = dat[sortperm(dat, :X), :];

dat = DataFrame(X=[1, 2, 3, 1], Y=[7, 19, 2, 2]) = 4×2 DataFrame
│ Row │ X     │ Y     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 7     │
│ 2   │ 2     │ 19    │
│ 3   │ 3     │ 2     │
│ 4   │ 1     │ 2     │
dat = dat[idxX, :] = 4×2 DataFrame
│ Row │ X     │ Y     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 7     │
│ 2   │ 1     │ 2     │
│ 3   │ 2     │ 19    │
│ 4   │ 3     │ 2     │
dat = dat[sortperm(dat, :X), :] = 4×2 DataFrame
│ Row │ X     │ Y     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 1     │ 7     │
│ 2   │ 1     │ 2     │
│ 3   │ 2     │ 19    │
│ 4   │ 3     │ 2     │


In [20]:
# Sort in reverse order of Y using order(:colname, rev=true)
dat[sortperm(dat, order(:Y, rev=true)), :]

4×2 DataFrame
│ Row │ X     │ Y     │
│     │ Int64 │ Int64 │
├─────┼───────┼───────┤
│ 1   │ 2     │ 19    │
│ 2   │ 1     │ 7     │
│ 3   │ 1     │ 2     │
│ 4   │ 3     │ 2     │